# description: Where to export to
# type: string
# required: true
dest: TODO

# description: should body be included
# type: boolean
# includeBody: true

# description: should stubs be included
# type: boolean
# includeStubs: TODO

# description: undefined
# type: array
# ignore: TODO

# description: include or exclude certain vaults
# type: object
# vaults: TODO